FROM node:20

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json
RUN npm ci --include=dev

COPY . /app/
# RUN chmod +x /app/docker.sh

USER root

#install playwright browser
RUN npx playwright install --with-deps

#set playwright to use system-installed browser
ENV PLAYWRIGHT_BROWSERS_PATH=0